### ISSUE TITLE
Boundhub extension issues

### ISSUE THREAD

**Issue by Dunk926** [tasadar2/Bondage-College-Cheats#4]
I was wondering if you could take a look at the extension if you created for Boundhub. It seems to not be working now.

**Comment by cheese529** [comment]
Yup the extension no longer seems to be working. @tasadar2 Can you please take a look at it whenever you get the chance? That extension literally the only thing that made that site still worth using. I would literally pay you money to fix it.

**Comment by tasadar2** [comment]
Seems to be working.

**Comment by cheese529** [comment]
@tasadar2 It's not working again and when I visit https://transpiria.com/ I get a 504 gateway time-out.  Is there anyway at all for you to fix this? This script you made is literally the only thing that made boundhub worth using since 70% of the videos are locked behind private filter and most users are gatekeeping or inactive now.

**Comment by cheese529** [comment]
Thank you so much for fixing it dude :)

**Comment by RUiN-jiarun** [comment]
Seems like there's another 502 gateway time-out happened @tasadar2 orz 
Please fix this thank you so much! @tasadar2
